---
- hosts: vagrant-centos
  become: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
        state: latest
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

# This playbook uses two external ansible galaxy roles
# Install geerlingguy.pip and geerlingguy.docker roles before executing this paybook
#
# Playbook was tested with following versions:
# $ ansible-galaxy list | egrep "pip|docker"
# - geerlingguy.docker, 2.5.3
# - geerlingguy.pip, 1.3.0
